export const LOAD_AUTHORS_SUCCESS =  'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHORS_ERROR =  'LOAD_AUTHORS_ERROR';

export const LOAD_COURSES_SUCCESS =  'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_ERROR =  'LOAD_COURSES_ERROR';
export const CREATE_COURSE_SUCCESS =  'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS =  'UPDATE_COURSE_SUCCESS';
export const SAVE_COURSE_ERROR =  'SAVE_COURSE_ERROR';